---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tmc-flux-poc
  namespace: postgres-instances
spec:
  interval: 1m
  url: https://github.com/jlafata/tmc-flux-poc.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-deployments
  namespace: dev-space
spec:
  interval: 5m0s
  path: ./tap-prod-app-deployments
  prune: true
  sourceRef:
    kind: GitRepository
    name: tmc-flux-poc
