---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: node-database-accelerator-test
  namespace: accelerator-system
spec:
  git:
    ref:
      branch: main
    url: https://github.com/jlafata/node-database-accelerator.git
    secretRef:
      name: git-secret
